import { StyleSheet, Platform, Dimensions } from 'react-native';

export const getGlobalStyles = (theme) => StyleSheet.create({
  // --- ESTRUTURAS GERAIS --- //
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 25,
    paddingTop: 40,
    backgroundColor: theme.background,
  },
  safeArea: {
    flex: 1,
    backgroundColor: theme.background,
  },
  conteudo: {
    flex: 1,
    backgroundColor: theme.background,
  },
  conteudoContainer: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 20,
  },

  // T01_Splash - Padronizada com a Home
  containerSplash: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.background,
  },
  texto2: {
    fontSize: 18,
    color: theme.primary,
    fontWeight: '700',
    marginHorizontal: 40,
    marginBottom: 20,
  },
  texto3: {
    fontSize: 15,
    color: theme.textPrimary,
    lineHeight: 24,
    marginBottom: 40,
    paddingLeft: 60,
    paddingRight: 60,
    paddingHorizontal: 30,
  },
  imagem: {
    marginBottom: 30,
    width: 300,
    height: 200,
    resizeMode: 'contain',
  },
  texto_botao: {
    color: theme.buttonTextInverse,
    fontSize: 17,
    fontWeight: '700',
  },
  botao2: {
    backgroundColor: theme.background,
    width: '80%',
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: theme.secondary,
  },
  texto_botao2: {
    color: theme.secondary,
    fontSize: 17,
    fontWeight: '700',
  },

  // --- TEXTOS E TÍTULOS (Login/Cadastro/Redefinir) //
  title: {
    fontSize: 26,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 20,
    color: theme.primary,
  },
  subtitle: {
    fontSize: 15,
    textAlign: 'center',
    color: theme.textSecondary,
    marginBottom: 15,
  },
  texto_bem_vindo: {
    color: theme.primary,
    fontWeight: 'bold',
    fontSize: 28,
    textAlign: 'center',
    marginTop: 40,
  },
  texto_acesso_conta: {
    color: theme.textMuted,
    fontSize: 15,
    textAlign: 'center',
    marginTop: 10,
    paddingBottom: 50,
  },

  // --- INPUTS PADRONIZADOS ---
  input: {
    backgroundColor: theme.inputBackground,
    borderWidth: 1.5,
    borderColor: theme.textSecondary,
    borderRadius: 15,
    paddingHorizontal: 20,
    height: 55,
    width: '95%',
    alignSelf: 'center',
    marginTop: 15,
    color: theme.textPrimary,
  },
  inputContainer: { 
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.inputBackground,
    borderWidth: 1.5,
    borderColor: theme.textSecondary,
    borderRadius: 15,
    paddingHorizontal: 15,
    height: 55,
    width: '95%',
    alignSelf: 'center',
    marginTop: 15,
  },

  // --- BOTÕES ---
  botao_entrar: { 
    backgroundColor: theme.secondary,
    height: 55,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 25,
    width: '90%',
    alignSelf: 'center',
    elevation: 3,
  },
  buttonPrimary: { 
    backgroundColor: theme.secondary,
    padding: 15,
    borderRadius: 10,
    marginTop: 10,
    alignItems: 'center',
  },
  buttonText: {
    color: theme.buttonTextInverse,
    fontWeight: 'bold',
    fontSize: 18,
  },
  texto_botao_entrar: {
    color: theme.buttonTextInverse,
    fontSize: 18,
    fontWeight: 'bold',
  },

  // --- COMPONENTES ESPECÍFICOS (Cadastro) --- //
  tipoContainer: {
    flexDirection: "row",
    marginBottom: 20,
    justifyContent: 'center'
  },
  tipoBtn: {
    flex: 1,
    padding: 10,
    borderWidth: 1.5,
    borderColor: theme.textMuted,
    borderRadius: 10,
    alignItems: "center",
    marginHorizontal: 5,
    backgroundColor: theme.inputBackground
  },
  tipoSelecionado: {
    borderColor: theme.primary,
    backgroundColor: theme.badgeAtivaBg,
  },

  // --- COMPONENTES ESPECÍFICOS (Home Doador) ---
  header: {
    backgroundColor: theme.headerBackground,
    paddingHorizontal: 20,
    paddingBottom: 14,
    flexDirection: 'column', 
    alignItems: 'center',    
    justifyContent: 'center',  
    height: 260,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'center', 
    alignItems: 'center',
    width: '95%',
  },
  saudacao: {
    fontSize: 25,
    fontWeight: '700',
    color: theme.headerTextInverse,
    letterSpacing: 0.2,
    paddingBottom: 25, 
  },
  nomeRestaurante: {
    fontSize: 16,
    color: theme.headerTextInverse,
    paddingBottom: 5,
  },
  menuIcone: {
    padding: 4,
  },
  menuIconeTexto: {
    fontSize: 35,
    color: theme.headerTextInverse,
  },

  // Cards de resumo
  resumoContainer: {
    flexDirection: 'row',
    gap: 12,
  },
  resumoCard: {
    flex: 1,
    backgroundColor: theme.mode === 'dark' ? theme.cardBackground : 'rgba(255,255,255,0.3)',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  resumoCardDestaque: {
    backgroundColor: theme.secondary,
  },
  resumoNumero: {
    fontSize: 28,
    fontWeight: '700',
    color: theme.textPrimary,
    alignItems: 'center',
  },
  resumoLabel: {
    fontSize: 13,
    color: theme.textSecondary,
    marginTop: 2,
    alignItems: 'center',
  },
  resumoNumeroDestaque: {
    fontSize: 28,
    fontWeight: '700',
    color: theme.buttonTextInverse,
    alignItems: 'center',
  },
  resumoLabelDestaque: {
    fontSize: 13,
    color: theme.mode === 'dark' ? 'rgba(0,0,0,0.75)' : 'rgba(255,255,255,0.85)',
    marginTop: 2,
    alignItems: 'center',
  },

  // Conteúdo
  conteudoHomeDoador: {
    flex: 1,
    backgroundColor: theme.background,
    marginTop: -1,
  },
  conteudoContainerHomeDoador: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 20,
  },
  botaoNovaDoacao: {
    backgroundColor: theme.secondary,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: 28,
    elevation: 4,
  },
  botaoNovaDoacaoTexto: {
    fontSize: 17,
    fontWeight: '700',
    color: theme.buttonTextInverse,
    letterSpacing: 0.3,
  },
  secaoTitulo: {
    fontSize: 11,
    fontWeight: '700',
    color: theme.textMuted,
    letterSpacing: 1.2,
    marginBottom: 12,
  },
  cardSolicitacao: {
    backgroundColor: theme.cardBackground,
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: theme.secondary,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  nomeOng: {
    fontSize: 15,
    fontWeight: '700',
    color: theme.textPrimary,
    flex: 1,
    marginRight: 8,
  },
  descricaoSolicitacao: {
    fontSize: 13,
    color: theme.textSecondary,
    marginBottom: 14,
  },
  badgePendente: {
    backgroundColor: theme.badgeBg,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: theme.badgeBorder,
  },
  badgePendenteTexto: {
    fontSize: 11,
    fontWeight: '600',
    color: theme.badgeText,
  },
  botoesCard: {
    flexDirection: 'row',
    gap: 10,
  },
  botaoAceitar: {
    flex: 1,
    backgroundColor: theme.primary,
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: 'center',
  },
  botaoAceitarTexto: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.buttonTextInverse,
  },
  botaoRecusar: {
    flex: 1,
    backgroundColor: theme.background,
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: theme.secondary,
  },
  botaoRecusarTexto: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.secondary,
  },
  emptyState: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  emptyStateTexto: {
    fontSize: 14,
    color: theme.textMuted,
  },

  // Barra de navegação
  navBar: {
    flexDirection: 'row',
    backgroundColor: theme.cardBackground,
    borderTopWidth: 1,
    borderTopColor: theme.badgeBorder,
    paddingBottom: 30,
    paddingHorizontal: 8,
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 2,
  },
  navIcone: {
    fontSize: 20,
    marginBottom: 2,
    opacity: 0.5,
    color: theme.textPrimary,
  },
  navIconeAtivo: {
    fontSize: 20,
    marginBottom: 2,
    color: theme.primary,
  },
  navLabel: {
    fontSize: 10,
    color: theme.textMuted,
    fontWeight: '500',
  },
  navLabelAtivo: {
    fontSize: 10,
    color: theme.primary,
    fontWeight: '700',
  },
  backBtn: {
    backgroundColor: theme.backBtnBg,
    borderRadius: 18,
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backBtnTexto: {
    color: theme.headerTextInverse,
    fontSize: 18,
    fontWeight: '700',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitulo: {
    fontSize: 11,
    fontWeight: '700',
    color: theme.headerTextInverse,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarArea: {
    alignItems: 'center',
    marginBottom: 6,
  },
  avatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderWidth: 3,
    borderColor: 'rgba(255,255,255,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  avatarEmoji: {
    fontSize: 30,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 20,
    marginTop: 5,
    marginBottom: 4,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 24,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: theme.textMuted,
  },
  infoIcone: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: theme.iconBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoIconeTexto: {
    fontSize: 16,
  },
  infoLabel: {
    fontSize: 11,
    color: theme.textMuted,
    fontWeight: '600',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  infoValor: {
    fontSize: 14,
    color: theme.textPrimary,
    fontWeight: '500',
    marginTop: 2,
  },
  sobreRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
  },
  doacaoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  doacaoIconeBox: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: theme.iconBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeAtiva: {
    backgroundColor: theme.badgeAtivaBg,
    borderColor: theme.badgeAtivaBorder,
  },
  badgeAtivaTexto: {
    color: theme.badgeAtivaText,
  },
  cardSelecionado: {
    position: 'absolute',
    bottom: 12, left: 16, right: 16,
    backgroundColor: theme.cardBackground,
    borderRadius: 18,
    padding: 16,
    borderWidth: 1.5,
    borderColor: theme.secondary,
    elevation: 8,
    shadowColor: theme.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
  },
  cardLabel: {
    fontSize: 10, fontWeight: '700',
    color: theme.secondary, letterSpacing: 1,
    textTransform: 'uppercase', marginBottom: 4,
  },
  cardNome: {
    fontSize: 22, fontWeight: '700',
    color: theme.textPrimary, marginBottom: 8, lineHeight: 26,
  },
  cardInfoRow: {
    flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 2,
  },
  cardInfoIcone: { 
    fontSize: 13,
  },

  //T10//
  content: {
    padding: 20,
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: theme.cardBackground,
    borderWidth: 1,
    borderColor: theme.secondary,
    borderRadius: 10,
    paddingVertical: 15,
    marginBottom: 25,
  },
  statBox: {
    alignItems: 'center',
  },
  statNumber: {
    fontSize: 20,
    fontWeight: 'bold',
    color: theme.textPrimary,
  },
  statLabel: {
    fontSize: 12,
    color: theme.textSecondary,
  },
  card: {
    flexDirection: 'row',
    backgroundColor: theme.cardBackground,
    borderWidth: 1,
    borderColor: theme.secondary,
    borderRadius: 10,
    padding: 10,
    marginBottom: 15,
    alignItems: 'center',
  },
  cardInfo: {
    flex: 1,
    marginLeft: 15,
    justifyContent: 'center',
  },
  statusButton: {
    backgroundColor: theme.primary,
    borderRadius: 15,
    paddingVertical: 5,
    alignItems: 'center',
  },
  statusText: {
    color: theme.buttonTextInverse,
    fontWeight: 'bold',
  },
  tabBar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: theme.cardBackground,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: theme.badgeBorder,
  },
  tabItem: {
    alignItems: 'center',
  },
  tabText: {
    fontSize: 10,
    color: theme.textPrimary,
  },

  //T11//
  menuIcon: {
    position: 'absolute',
    right: 20,
    top: 20,
  },
  name: {
    fontSize: 22,
    fontWeight: 'bold',
    color: theme.textPrimary,
    marginTop: 10,
  },
  stat: {
    alignItems: 'center',
    marginHorizontal: 20,
  },
  menu: {
    marginTop: 20,
    paddingHorizontal: 20,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: theme.badgeBorder,
  },
  menuText: {
    marginLeft: 15,
    fontSize: 16,
    color: theme.textPrimary,
  },
  deleteText: {
    textAlign: 'center',
    color: theme.secondary,
    marginTop: 10,
  },
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: theme.cardBackground,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: theme.badgeBorder,
    marginTop: 'auto',
  },
  navText: {
    fontSize: 12,
    color: theme.textPrimary,
  },

  //T13 e T14//
  tag: {
    backgroundColor: theme.cardBackground,
    padding: 6,
    borderRadius: 8,
    marginRight: 5,
    marginBottom: 5,
    color: theme.textPrimary,
  },
  titulo: {
    fontSize: 22,
    fontWeight: 'bold',
    color: theme.primary,
  },
  label: {
    fontSize: 14,
    fontWeight: 'bold',
    color: theme.textPrimary,
    marginTop: 10,
    marginBottom: 5,
  },
  label_input: {
    backgroundColor: theme.inputBackground,
    padding: 10,
    borderRadius: 10,
    marginBottom: 10,
    color: theme.gray,
  },
  linha: {
    flexDirection: 'row',
    display: 'flex',
    flexWrap: 'wrap',
    padding: 10,
    marginBottom: 10,
    backgroundColor: theme.inputBackground,
    borderRadius: 10,
    borderWidth: 3,
    borderColor: theme.secondary,
  },
  nome: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.primary,
  },
  disponivel: {
    color: theme.primary,
    marginBottom: 10,
  },
  textoCard: {
    color: theme.textSecondary,
  },
  container_icone_voltar_contato: {
    width: '100%',
    alignItems: 'center',
    flexDirection: 'row',
    display: 'flex',
    flexWrap: 'wrap',
    marginBottom: 10,
  },

  // Componentes específicos (T06_CadastrarDoacao)
  header_cadastro: {
    backgroundColor: theme.headerBackground,
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? 16 : 8,
    paddingBottom: 30,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    height: 100,
    flexDirection: 'row',
  },
  headerTituloCentralizado: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'left',
    paddingTop: Platform.OS === 'android' ? 5 : 15,
  },
  tituloCadastro: {
    fontSize: 24,
    fontWeight: '700',
    color: theme.headerTextInverse,
  },
  menuIconeAbsoluto: {
    position: 'absolute',
    right: 20,
    top: Platform.OS === 'android' ? 25 : 35,
    padding: 4,
  },
  conteudoFormulario: {
    paddingHorizontal: 25,
    paddingTop: 10,
    paddingBottom: 40,
  },
  labelCadastro: {
    fontSize: 16,
    color: theme.textPrimary,
    marginBottom: 8,
    marginTop: 15,
  },
  inputCadastro: {
    backgroundColor: theme.inputBackground,
    borderWidth: 1.5,
    borderColor: theme.secondary,
    borderRadius: 15,
    paddingHorizontal: 15,
    height: 55,
    color: theme.textPrimary,
    fontSize: 16,
  },
  rowCadastro: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  inputMetade: {
    flex: 1,
    textAlign: 'center',
    color: theme.textPrimary,
  },
  espacoEntreInputs: {
    width: 15,
  },
  inputCadastroIcone: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.inputBackground,
    borderWidth: 1.5,
    borderColor: theme.secondary,
    borderRadius: 15,
    paddingHorizontal: 15,
    height: 55,
  },
  inputSemBorda: {
    flex: 1,
    color: theme.textPrimary,
    fontSize: 16,
  },
  inputFoto: {
    backgroundColor: theme.transparent,
    borderWidth: 1.5,
    borderColor: theme.textMuted,
    borderStyle: 'dashed',
    borderRadius: 15,
    height: 80,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
  },
  textoFoto: {
    color: theme.textSecondary,
    fontSize: 16,
  },

  // --- COMPONENTES ESPECÍFICOS (Home Receptor) --- //
  headerReceptor: {
    backgroundColor: theme.headerBackground,
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? 25 : 15,
    paddingBottom: 25,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  locationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  locationIcone: {
    fontSize: 22,
    marginRight: 5,
    color: theme.headerTextInverse,
  },
  locationText: {
    fontSize: 22,
    fontWeight: '700',
    color: theme.headerTextInverse,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.inputBackground,
    borderWidth: 1.5,
    borderColor: theme.secondary,
    borderRadius: 15,
    marginHorizontal: 20,
    marginTop: 20,
    paddingHorizontal: 15,
    height: 50,
  },
  searchIcon: {
    fontSize: 18,
    color: theme.textSecondary,
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 16,
    color: theme.textPrimary,
  },
  filtersRow: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    marginTop: 15,
    marginBottom: 20,
    gap: 10,
    flexGrow: 1,
    justifyContent: 'center',
  },
  filterBtn: {
    borderWidth: 1,
    borderColor: theme.filtroBorder,
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 12,
    backgroundColor: theme.inputBackground,
    justifyContent: 'center',
  },
  filterBtnActive: {
    backgroundColor: theme.primary,
    borderColor: theme.primary,
  },
  filterText: {
    color: theme.textPrimary,
    fontSize: 13,
  },
  filterTextActive: {
    color: theme.buttonTextInverse,
    fontSize: 13,
  },
  cardReceptor: {
    flexDirection: 'row',
    backgroundColor: theme.cardBackground,
    borderWidth: 1.2,
    borderColor: theme.filtroBorder,
    borderRadius: 10,
    marginHorizontal: 20,
    marginBottom: 15,
    padding: 10,
    elevation: 2,
  },
  cardImage: {
    width: 100,
    height: 100,
    borderRadius: 8,
    backgroundColor: theme.cardImageBg, 
  },
  cardContent: {
    flex: 1,
    marginLeft: 15,
    justifyContent: 'center',
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '500',
    color: theme.textPrimary,
    marginBottom: 2,
  },
  cardLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  cardDistanceIcon: {
    fontSize: 14,
    color: theme.secondary,
  },
  cardDistanceText: {
    fontSize: 14,
    color: theme.textPrimary,
    marginLeft: 2,
  },
  btnDetalhes: {
    backgroundColor: theme.secondary,
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 20,
    alignSelf: 'flex-start',
  },
  btnDetalhesText: {
    color: theme.buttonTextInverse,
    fontSize: 14,
  },

  container_contato: {
    flex: 1,
    padding: 30,
    backgroundColor: theme.cardBackground,
    justifyContent: 'center',
    borderRadius: 40,
  },
  view_texto_contato: {
    alignItems: 'center',
    marginBottom: 10,
  },
  texto_contato: {
    color: theme.verdeContato,
    fontWeight: 'bold',
    fontSize: 24,
    textAlign: 'center',
  },
  subtitulo: {
    textAlign: 'center',
    color: theme.marromContato,
    marginBottom: 30,
    fontSize: 16,
  },
  input_contato: {
    flex: 1,
    fontSize: 16,
    color: theme.textPrimary,
  },
  botao: {
    backgroundColor: theme.secondary,
    width: '100%',
    height: 55,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    marginTop: 10,
    elevation: 5,
    shadowColor: theme.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
  },
  view_requisitos: {
    marginTop: 30,
  },
  texto_requisito_titulo: {
    color: theme.marromContato,
    textAlign: 'center',
    marginBottom: 15,
    fontSize: 16,
  },
  item_requisito: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 5,
  },
  texto_item: {
    color: theme.textSecondary,
    fontSize: 15,
  },
  footer_texto: {
    marginTop: 40,
    fontSize: 12,
    color: theme.marromContato,
    textAlign: 'center',
  },
  inputPequeno: {
    borderWidth: 2,
    borderColor: theme.secondary,
    borderRadius: 10,
    padding: 10,
    width: 80,
    textAlign: 'center',
    color: theme.textPrimary,
  },
  unidades: {
    borderWidth: 2,
    borderColor: theme.secondary,
    borderRadius: 10,
    padding: 10,
    justifyContent: 'center',
  },
  inputGrande: {
    borderWidth: 2,
    borderColor: theme.secondary,
    borderRadius: 10,
    padding: 10,
    color: theme.textPrimary,
  },
  textoBotao: {
    color: theme.buttonTextInverse,
    fontWeight: 'bold',
  },

  // --- COMPONENTES ESPECÍFICOS (T19_HistoricoReceptor) --- //
  headerHistorico: {
    backgroundColor: theme.headerBackground,
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? 25 : 15,
    paddingBottom: 25,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTituloContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  backIcon: {
    fontSize: 26,
    color: theme.headerTextInverse,
  },
  tituloHistorico: {
    fontSize: 24,
    fontWeight: '700',
    color: theme.headerTextInverse,
    marginLeft: 15,
  },
  cardResumoHistorico: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: theme.cardBackground, 
    borderWidth: 1.5,
    borderColor: theme.secondary,
    borderRadius: 8,
    marginHorizontal: 20,
    marginTop: 25,
    marginBottom: 25,
    paddingVertical: 18,
  },
  resumoHistoricoItem: {
    alignItems: 'center',
  },
  resumoHistoricoValor: {
    fontSize: 26,
    color: theme.textPrimary,
  },
  resumoHistoricoLabel: {
    fontSize: 14,
    color: theme.textPrimary,
    marginTop: 2,
  },
  cardHistorico: {
    flexDirection: 'row',
    backgroundColor: theme.cardBackground,
    borderWidth: 1.5,
    borderColor: theme.secondary,
    borderRadius: 8,
    marginHorizontal: 20,
    marginBottom: 15,
    padding: 10,
  },
  cardContentHistorico: {
    flex: 1,
    marginLeft: 15,
    justifyContent: 'center',
  },
  btnConcluido: {
    backgroundColor: theme.btnConcluidoBg, 
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 20,
    alignSelf: 'flex-start',
    marginTop: 15,
  },
  btnConcluidoText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '500',
  },

  //Tela 17 Meus pedidos
  filtrosContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    marginTop: 25,
    marginBottom: 20,
    paddingHorizontal: 20,
    backgroundColor: theme.transparent,
  },
  filtroBotao: {
    borderWidth: 1,
    borderColor: theme.filtroBorder,
    borderRadius: 6,
    paddingVertical: 4,
    paddingHorizontal: 12,
    backgroundColor: theme.transparent,
  },
  filtroBotaoAtivo: {
    backgroundColor: theme.primary,
  },
  filtroTexto: {
    color: theme.textPrimary,
    fontSize: 14,
  },
  filtroTextoAtivo: {
    color: theme.buttonTextInverse,
  },
  cardAzul: {
    borderWidth: 2,
    borderColor: theme.cardAzulBorder,
  },
  cardLaranja: {
    borderWidth: 1,
    borderColor: theme.secondary, 
  },
  btnAceito: {
    backgroundColor: theme.btnAceitoBg, 
    borderRadius: 20,
    paddingVertical: 6,
    alignItems: 'center',
    marginRight: 10,
  },
  btnPendente: {
    backgroundColor: theme.btnPendenteBg, 
    borderRadius: 20,
    paddingVertical: 6,
    alignItems: 'center',
    marginRight: 10,
  },
  btnTextoBranco: {
    color: '#FFFFFF',
    fontSize: 14,
  },
});